### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by dancerphil** [starkwang/Spider#1]
尝试：
npm install -> node index.js -> http://localhost:3000/
console.log 报错：1、body undefined 2、syntax error & 403

然后又尝试：
cd client -> npm install -> gulp -> ...
并没有用

求解正确的打开方式。

**Comment by starkwang** [comment]
我刚才更新了一下代码，你pull一下

client里的代码是已经build好的，不需要构建了

config.js里要填入自己目前的cookie

**Comment by starkwang** [comment]
我刚才自己重新跑了一遍流程是可以用的，config.js里务必填上自己的cookie

README我有空再补吧/w\

**Comment by starkwang** [comment]
输入框里填入用户页的url
比如  https://www.zhihu.com/people/starkwei

**Comment by dancerphil** [comment]
fetchFollowerOrFollowee.js
line: 36
那里也需要改吧，从cookie里面拉出来，也许还有些地方需要改的。（这个地方的修改包含在我pull 里了）

反正的反，我还是没跑起来，403

我构造了一个请求，在chrome地址栏请求是可以的，但是node 和postman 都显示403，这可能是什么原因

**Comment by dancerphil** [comment]
20160323，已经可以运行
