### ISSUE TITLE
效率：spider 遇到大V时，有点崩

### ISSUE THREAD

**Issue by dancerphil** [starkwang/Spider#3]
比如70W关注的黄继新，我和他互相关注，导致爬上一万年

**Comment by starkwang** [comment]
这个问题除了加大并发数以外。。。暂时没有解决方法。。。
知乎提供的拉取关注者or关注的人的api只能一次拉取20个。。。

**Comment by dancerphil** [comment]
可以只爬关注了谁，也可以构建出朋友关系，搜索深度为相差2，而且搜到了自己，说明是互相关注。

就这么一想，也不知可不可行

**Comment by starkwang** [comment]
嗯有道理，关注的人很少有数量过万的，这样的话可以避免粉丝过多的问题，我有时间做一下这个feature。

2层搜索的话有中间数据，就需要加个数据库了，不过redis这种轻量级的就够了

**Comment by Willian-Zhang** [comment]
我正在給它加數據庫。
https://github.com/Willian-Zhang/Zhihu-Spider/tree/seprate-fetch-display

**Comment by dancerphil** [comment]
@Willian-Zhang 尽量把特性分开交 PR 。

说到数据库，你是打算 redis 吗？最近喜欢 nedb ，嵌入式，性能肯定不如 redis ，但是这个项目的瓶颈根本不在数据库性能，而是知乎API的性能。

**Comment by Willian-Zhang** [comment]
我是打算mongodb 2333 因為考慮到 schema 還沒確定

**Comment by Willian-Zhang** [comment]
mongo 測試了一下大概10小時（不確定）可以爬 3（不包括自己）層 274732 人
